// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * Identifier for an exam.
 */
export type ExamId = number

/**
 * AI-generated (GPT-5.3-codex).
 */
export type InitSolverError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Solver: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Recv: string }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type LockedTimetableSlot = { session_id: SessionId; timeslot_id: TimeslotId }

export type NewTimetableUpdate = 
/**
 * Key: session ID
 * Value: timeslot ID
 * 
 * (Specta doesn't like non-number/string keys)
 */
{ Timetable: Partial<{ [key in number]: TimeslotId }> } | "Done"

/**
 * Identifier for a session.
 */
export type SessionId = number

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SolveSessionControlError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Send: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ InvalidSessionId: number }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SolveSessionStart = { session_id: number }

export type SqlBatchQuery = { sql: string; params: SqlParam[]; method: string }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SqlError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ SqlProxy: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string }

export type SqlParam = "Null" | { Bool: boolean } | { Int: number } | { Float: number } | { Text: string }

export type SqlQueryResult = { rows: SqlValue[][] }

export type SqlValue = "Null" | { Bool: boolean } | { Int: number } | { Float: number } | { Text: string } | { Blob: number[] }

/**
 * Identifier for a timeslot.
 */
export type TimeslotId = number

/**
 * Data to generate a timetable PDF
 */
export type TimetableData = { 
/**
 * The name of the school
 */
schoolName: string; 
/**
 * The title of the timetable
 */
title: string; 
/**
 * The grades to include in the timetable
 */
grades: number[]; 
/**
 * The days that make up the timetable
 */
days: TimetableDay[] }

/**
 * A day in the timetable
 */
export type TimetableDay = { 
/**
 * The date of the day, in ISO 8601 format
 */
date: string; 
/**
 * The sessions that occur on this day
 */
sessions: TimetableSession[] }

/**
 * An exam entry in the timetable session
 */
export type TimetableExamEntry = { 
/**
 * The session ID of the exam
 */
sessionId: number; 
/**
 * The exam ID of the exam
 */
examId: ExamId; 
/**
 * The grade of the exam
 */
grade: number; 
/**
 * The subject of the exam
 */
subject: string; 
/**
 * Custom name for the exam. Replaces <Paper number> in the display
 */
examName: string | null; 
/**
 * The start of the exam, formatted as "hh:mm"
 */
startTime: string; 
/**
 * The end of the exam, formatted as "hh:mm"
 */
endTime: string; 
/**
 * The exam paper number
 */
paperNumber: number; locked: boolean }

/**
 * A session in the timetable
 */
export type TimetableSession = { 
/**
 * The session number (currently either 1 or 2)
 */
sessionNumber: number; 
/**
 * The timeslot ID of the session
 */
timeslotId: TimeslotId; 
/**
 * The exams that occur in this session
 */
exams: TimetableExamEntry[] }

const ARGS_MAP = { '':'{"generate_timetable_pdf":["data"],"pause_solve_session":["session_id"],"solve_single":["locked_slots"],"sql":["sql","params","method"],"sql_batch":["queries"],"start_solve_session":["on_new_timetable","locked_slots"],"stop_solve_session":["session_id"]}' }
export type Router = { "": {generate_timetable_pdf: (data: TimetableData) => Promise<null>, 
pause_solve_session: (sessionId: number) => Promise<null>, 
solve_single: (lockedSlots: LockedTimetableSlot[]) => Promise<Partial<{ [key in number]: TimeslotId }>>, 
sql: (sql: string, params: SqlParam[], method: string) => Promise<SqlQueryResult>, 
sql_batch: (queries: SqlBatchQuery[]) => Promise<SqlQueryResult[]>, 
start_solve_session: (onNewTimetable: TAURI_CHANNEL<NewTimetableUpdate>, lockedSlots: LockedTimetableSlot[]) => Promise<SolveSessionStart>, 
stop_solve_session: (sessionId: number) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
