#let data = json.decode(sys.inputs.data)

#set document(
  title: data.title,
  author: data.schoolName,
)

#show link: underline

// 9pt variant for all body text
#set text(font: "Google Sans Flex 9pt", size: 10pt, fill: black)

// Swap to optically-appropriate variants at display sizes
#let display-text(body, size: 18pt) = text(font: "Google Sans Flex 24pt", size: size, body)

#set page(
  paper: "a4",
  margin: (x: 1cm, top: 1cm, bottom: 1.7cm),
  footer: context grid(
    columns: (1fr, 2fr, 1fr),
    align: (left, center, right),

    // left
    text(8pt, fill: luma(120))[#data.schoolName: #data.title],
    // center
    text(
      8pt,
      fill: luma(120),
    )[Generated by #link("https://timetable.wobbl.in")[exam-timetable] which is #sym.copyright #link("https://wobbl.in")[S. Singh] (2026) under the #link("https://github.com/Suya1671/exam-timetable/blob/main/LICENSE")[MIT License].],
    // right
    text(8pt, fill: luma(120))[Page #counter(page).display() / #counter(page).final().at(0)],
  ),
)

#grid(
  columns: (1fr, 1fr),
  align: (left, right),

  // left
  display-text(size: 18pt)[#underline[#data.title]],
  // right
  display-text(size: 18pt)[#data.schoolName],
)

#v(1em)

#let weeks = data.days.map(d => d.weekNumber).dedup()

#let main-bg = white
#let offset-bg = luma(90%)

// Iterators my beloved
#let maxPaperNumber(grade, subject) = {
  data
    .days
    .map(day => day.sessions)
    .flatten()
    .map(sessions => sessions.at("exam", default: none))
    .filter(session => session != none)
    .filter(session => session.grade == grade and session.subject == subject)
    .map(subject => subject.paperNumber)
    .reduce((acc, x) => calc.max(acc, x))
}

#let bold-stroke = 2pt + black

// y=1 -> Date, Session, Grades... etc roow
#show table.cell.where(y: 1): set text(size: 12pt)

#for week in weeks {
  table(
    columns: (auto, auto, 1fr),
    stroke: black,
    align: center + horizon,
    table.hline(stroke: bold-stroke),
    table.vline(stroke: bold-stroke),

    table.header(
      table.cell(
        colspan: 3,
        fill: offset-bg,
        align: left,
        inset: (left: 8pt),
        display-text(size: 16pt)[*Week #week*],
      ),
    ),

    table.hline(stroke: bold-stroke),
    table.vline(stroke: bold-stroke),

    // Column headers
    table.header(
      repeat: true,
      table.cell(fill: offset-bg)[*Date*],
      table.cell(fill: offset-bg)[*Session*],
      table.cell(fill: offset-bg)[*Exam*],
    ),

    ..{
      let cells = ()
      let daysInWeek = data.days.filter(day => day.weekNumber == week)

      for day in daysInWeek {
        cells.push(table.hline(stroke: bold-stroke))
        let parseDate(s) = toml(bytes("date = " + s)).date
        let date = parseDate(day.date)

        for (i, session) in day.sessions.enumerate() {
          let row-fill = if calc.odd(i) { offset-bg } else { main-bg }
          if i == 0 {
            cells.push(
              table.cell(
                rowspan: day.sessions.len(),
                breakable: false,
              )[*#date.display("[weekday]\n[day] [month repr:long]")*],
            )
          }

          cells.push(table.cell(fill: row-fill)[*Session #session.number*])

          if session.at("exam", default: none) != none {
            let exam = session.exam
            cells.push(
              table.cell(fill: row-fill, block(spacing: 0pt)[
                #text(size: 10pt)[
                  #exam.subject
                  #if exam.examName != none {
                    exam.examName
                  } else if maxPaperNumber(exam.grade, exam.subject) > 1 {
                    [P#exam.paperNumber]
                  }
                ]\
                #text(size: 8pt, fill: luma(30%))[#exam.startTime -- #exam.endTime]
              ]),
            )
          } else {
            let tile-size = 16pt
            cells.push(
              table.cell(fill: tiling(size: (tile-size, tile-size), relative: "parent")[
                // bg color
                #place(top + left, rect(fill: row-fill, stroke: none))

                // Modified from the hero tiling diagonal line
                #place(top + left, polygon(
                  fill: black.transparentize(10%),
                  stroke: none,
                  (tile-size - 1pt, 0pt),
                  (tile-size, 0pt),
                  (0pt, tile-size),
                  (0pt, tile-size - 1pt),
                ))

                #place(top + left, dx: tile-size - 1pt, dy: tile-size - 1pt, polygon(
                  fill: black.transparentize(10%),
                  stroke: none,
                  (1pt, 0pt),
                  (1pt, 1pt),
                  (0pt, 1pt),
                ))
              ])[],
            )
          }
        }
      }

      cells.push(table.hline(stroke: bold-stroke))

      cells
    },
  )
}
