// TODOs
// - Actual sizing system
// - Bold table borders
// - Add in logo support
// - Add in customisable font choice
#let data = json("data.json")

#pdf.attach("data.json", description: "Timetable data for import")

#set document(
  title: data.title,
  author: data.schoolName,
)

#show link: underline

#set page(
  paper: "a4",
  flipped: true,
  margin: (x: 1cm, y: 1cm),
  footer: context grid(
    columns: (1fr, 2fr, 1fr),
    align: (left, center, right),

    // left
    text(8pt, fill: luma(120))[#data.schoolName: #data.title],
    // center
    text(
      8pt,
      fill: luma(120),
    )[Generated by #link("https://github.com/Suya1671/exam-timetable")[exam-timetable] which is #sym.copyright #link("https://wobbl.in")[S. Singh] (2026) under the #link("https://github.com/Suya1671/exam-timetable/blob/main/LICENSE")[MIT License].],
    // right
    text(8pt, fill: luma(120))[Page #counter(page).display() / #counter(page).final().at(0)],
  ),
)

#set text(font: ("Arial", "Linux Biolinum", "sans-serif"), size: 10pt, fill: black)

#let render-exam(entry, is-last) = {}

#grid(
  columns: (1fr, 1fr, 1fr),
  align: (left, center, right),

  // left
  text(size: 18pt)[#data.schoolName],
  // center
  text(size: 18pt)[#underline[#data.title]],
)

#v(1em)

#let weeks = data.days.map(d => d.weekNumber).dedup()

#let main-bg = white
#let offset-bg = luma(90%)

// Iterators my beloved
#let maxPaperNumber(grade, subject) = {
  data
    .days
    .map(day => day.sessions)
    .flatten()
    .map(sessions => sessions.exams)
    .flatten()
    .filter(session => session.grade == grade and session.subject == subject)
    .map(subject => subject.paperNumber)
    .reduce((acc, x) => calc.max(acc, x))
}

#let bold-stroke = 2pt + black

// y=1 -> Date, Session, Grades... etc roow
#show table.cell.where(y: 1): set text(size: 12pt)

#for week in weeks {
  table(
    columns: (auto, auto) + data.grades.map(_ => 1fr),
    stroke: black,
    align: center + horizon,
    table.hline(stroke: bold-stroke),
    table.vline(stroke: bold-stroke),

    table.header(
      table.cell(
        colspan: 2 + data.grades.len(),
        fill: offset-bg,
        align: left,
        inset: (left: 8pt),
        text(size: 16pt)[*Week #week*],
      ),
    ),

    table.hline(stroke: bold-stroke),
    table.vline(stroke: bold-stroke),

    // Column headers
    table.header(
      repeat: true,
      table.cell(fill: offset-bg)[*Date*],
      table.cell(fill: offset-bg)[*Session*],
      ..data.grades.map(g => table.cell(fill: offset-bg)[*Grade #g*]),
    ),

    ..{
      let cells = ()
      let daysInWeek = data.days.filter(day => day.weekNumber == week)

      for day in daysInWeek {
        cells.push(table.hline(stroke: bold-stroke))
        let parseDate(s) = toml(bytes("date = " + s)).date
        let date = parseDate(day.date)

        for (i, session) in day.sessions.enumerate() {
          let row-fill = if calc.odd(i) { offset-bg } else { main-bg }
          if i == 0 {
            cells.push(
              table.cell(
                rowspan: day.sessions.len(),
                breakable: false
              )[*#date.display("[weekday]\n[day] [month repr:long]")*],
            )
          }

          cells.push(table.cell(fill: row-fill)[*Session #session.sessionNumber*])

          // Filter exams for each grade column
          for grade in data.grades {
            let grade-exams = session.exams.filter(e => e.grade == grade)
            let count = grade-exams.len()


            let tile-size = 10pt
            let cell-fill = if count == 0 {
              tiling(size: (tile-size, tile-size), relative: "parent")[
                // bg color
                #place(top + left, rect(fill: row-fill, stroke: none))

                // Modified from the hero tiling diagonal line
                #place(top + left, polygon(
                  fill: black.transparentize(10%),
                  stroke: none,
                  (tile-size - 1pt, 0pt),
                  (tile-size, 0pt),
                  (0pt, tile-size),
                  (0pt, tile-size - 1pt),
                ))

                #place(top + left, dx: tile-size - 1pt, dy: tile-size - 1pt, polygon(
                  fill: black.transparentize(10%),
                  stroke: none,
                  (1pt, 0pt),
                  (1pt, 1pt),
                  (0pt, 1pt),
                ))
              ]
            } else {
              row-fill
            }

            cells.push(
              table.cell(
                fill: cell-fill,
                if count > 0 {
                  for (i, exam) in grade-exams.enumerate() {
                    let is-last = i + 1 == grade-exams.len()
                    let spacing = 3pt

                    v(spacing)
                    block(spacing: 0pt)[
                      #text(size: 10pt)[
                        #exam.subject
                        #if exam.examName != none {
                          exam.examName
                        } else if maxPaperNumber(exam.grade, exam.subject) > 1 {
                          [P#exam.paperNumber]
                        }
                      ]\
                      #text(size: 8pt, fill: luma(30%))[#exam.startTime -- #exam.endTime]
                    ]
                    if not is-last {
                      v(spacing * 2)
                      line(length: 100%, stroke: 0.5pt + gray)
                    }
                    v(spacing)
                  }
                } else {
                  []
                },
              ),
            )
          }
        }
        cells.push(table.hline(stroke: bold-stroke))
      }

      cells
    }
  )

  pagebreak(weak: true)
}
