//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::{StudentId, SubjectId};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "enrolled_students")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub student_id: StudentId,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: SubjectId,

    #[sea_orm(
        belongs_to,
        from = "student_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub student: HasOne<super::students::Entity>,

    #[sea_orm(
        belongs_to,
        from = "subject_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub subject: HasOne<super::subjects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
