//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::{ExamId, SubjectId};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: ExamId,
    pub subject_id: SubjectId,
    pub paper: i32,
    pub duration_hours: Decimal,
    pub priority: i32,
    pub slots_required: i32,

    #[sea_orm(has_many)]
    pub allowed_timeslots: HasMany<super::exam_allowed_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub denied_timeslots: HasMany<super::exam_denied_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,

    #[sea_orm(
        belongs_to,
        from = "subject_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub subject: HasOne<super::subjects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
