//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod different_week_exams;
pub mod enrolled_students;
pub mod exam_allowed_timeslots;
pub mod exam_denied_timeslots;
pub mod exams;
pub mod same_day_exams;
pub mod sessions;
pub mod student_allowed_timeslots;
pub mod student_denied_timeslots;
pub mod students;
pub mod subject_allowed_timeslots;
pub mod subject_denied_timeslots;
pub mod subjects;
pub mod timeslots;
