//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::different_week_exams::Entity as DifferentWeekExams;
pub use super::enrolled_students::Entity as EnrolledStudents;
pub use super::exam_allowed_timeslots::Entity as ExamAllowedTimeslots;
pub use super::exam_denied_timeslots::Entity as ExamDeniedTimeslots;
pub use super::exams::Entity as Exams;
pub use super::same_day_exams::Entity as SameDayExams;
pub use super::sessions::Entity as Sessions;
pub use super::student_allowed_timeslots::Entity as StudentAllowedTimeslots;
pub use super::student_denied_timeslots::Entity as StudentDeniedTimeslots;
pub use super::students::Entity as Students;
pub use super::subject_allowed_timeslots::Entity as SubjectAllowedTimeslots;
pub use super::subject_denied_timeslots::Entity as SubjectDeniedTimeslots;
pub use super::subjects::Entity as Subjects;
pub use super::timeslots::Entity as Timeslots;
