//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::ExamId;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "same_day_exams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub first_slot_exam_id: ExamId,
    #[sea_orm(primary_key, auto_increment = false)]
    pub second_slot_exam_id: ExamId,
    #[sea_orm(column_type = "Text")]
    pub date: String,

    #[sea_orm(
        belongs_to,
        relation_enum = "FirstExam",
        from = "first_slot_exam_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub first_exam: HasOne<super::exams::Entity>,

    #[sea_orm(
        belongs_to,
        relation_enum = "SecondExam",
        from = "second_slot_exam_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub second_exam: HasOne<super::exams::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
