//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::{ExamId, SessionId};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: SessionId,
    pub exam_id: ExamId,
    pub sequence: i32,

    #[sea_orm(
        belongs_to,
        from = "exam_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub exam: HasOne<super::exams::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
