//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::StudentId;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: StudentId,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub grade: i32,

    #[sea_orm(has_many)]
    pub enrollments: HasMany<super::enrolled_students::Entity>,

    #[sea_orm(has_many)]
    pub allowed_timeslots: HasMany<super::student_allowed_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub denied_timeslots: HasMany<super::student_denied_timeslots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
