//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::id::{TimeslotId, TimeslotSlot};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "timeslots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: TimeslotId,
    #[sea_orm(column_type = "Text")]
    pub date: time::Date,
    pub slot: TimeslotSlot,

    #[sea_orm(has_many)]
    pub exam_allowed_timeslots: HasMany<super::exam_allowed_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub exam_denied_timeslots: HasMany<super::exam_denied_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub student_allowed_timeslots: HasMany<super::student_allowed_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub student_denied_timeslots: HasMany<super::student_denied_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub subject_allowed_timeslots: HasMany<super::subject_allowed_timeslots::Entity>,

    #[sea_orm(has_many)]
    pub subject_denied_timeslots: HasMany<super::subject_denied_timeslots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
