# Global Node/TypeScript tasks inherited by frontend projects
# https://moonrepo.dev/docs/concepts/tasks#task-inheritance

inheritedBy:
    languages: ['javascript', 'typescript']

fileGroups:
    sources:
        - "src/**/*"
    configs:
        - "package.json"
        - "tsconfig.json"
        - ".eslintrc*"
        - "prettier.config.*"
        - "/package.json"
        - "/pnpm-lock.yaml"
        - "/pnpm-workspace.yaml"
    tests:
        - "tests/**/*"

tasks:
    dev:
        command: "pnpm dev"
        preset: "server"
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    build:
        command: "pnpm build"
        inputs:
            - "@group(sources)"
            - "@group(configs)"
        outputs:
            - "build"

    check:
        command: "pnpm check"
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    lint:
        command: "eslint ."
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    format:
        command: "eslint . --fix"
        inputs:
            - "@group(sources)"
            - "@group(configs)"
