# Global Node/TypeScript tasks inherited by frontend projects
# https://moonrepo.dev/docs/concepts/tasks#task-inheritance

inheritedBy:
    languages: ['javascript', 'typescript']

fileGroups:
    sources:
        - "src/**/*"
    configs:
        - "package.json"
        - "tsconfig.json"
        - ".eslintrc*"
        - "/package.json"
        - "/pnpm-lock.yaml"
        - "/pnpm-workspace.yaml"
        - "/tsconfig.json"
        - "/tsconfig.options.json"
    tests:
        - "tests/**/*"

tasks:
    dev:
        command: "pnpm dev"
        preset: "server"
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    build:
        command: "pnpm build"
        inputs:
            - "@group(sources)"
            - "@group(configs)"
        outputs:
            - "build"

    check:
        command: "pnpm check"
        inputs:
            - "@group(sources)"
            - "@group(configs)"
        dependsOn:
            - typecheck

    lint:
        command: "eslint ."
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    format:
        command: "eslint . --fix"
        inputs:
            - "@group(sources)"
            - "@group(configs)"

    typecheck:
        command:
            - 'tsgo'
            # Use incremental builds with project references
            - '--build'
            # Always use pretty output
            - '--pretty'
            # Use verbose logging to see affected projects
            - '--verbose'
        inputs:
            - "@group(sources)"
            - "@group(configs)"
        dependsOn:
            - ^:typecheck
