// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ApiError = 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ SqlProxyError: string }

/**
 * AI-generated (GPT-5.2-codex).
 */
export type SqlParam = 
/**
 * AI-generated (GPT-5.2-codex).
 */
"Null" | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Bool: boolean } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Int: number } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Float: number } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Text: string }

/**
 * AI-generated (GPT-5.2-codex).
 */
export type SqlQueryResult = { rows: SqlValue[][] }

/**
 * AI-generated (GPT-5.2-codex).
 */
export type SqlValue = 
/**
 * AI-generated (GPT-5.2-codex).
 */
"Null" | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Bool: boolean } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Int: number } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Float: number } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Text: string } | 
/**
 * AI-generated (GPT-5.2-codex).
 */
{ Blob: number[] }

const ARGS_MAP = { '':'{"sql":["sql","params","method"]}' }
export type Router = { "": {sql: (sql: string, params: SqlParam[], method: string) => Promise<SqlQueryResult>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
