// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * AI-generated (GPT-5.3-codex).
 */
export type InitSolverError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Solver: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Recv: string }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type LockedTimetableSlot = { session_id: SessionId; timeslot_id: TimeslotId }

export type NewTimetableUpdate = 
/**
 * Key: session ID
 * Value: timeslot ID
 * 
 * (Specta doesn't like non-number/string keys)
 */
{ Timetable: Partial<{ [key in number]: TimeslotId }> } | "Done"

/**
 * Identifier for a session.
 */
export type SessionId = number

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SolveSessionControlError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ Send: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ InvalidSessionId: number }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SolveSessionStart = { session_id: number }

export type SqlBatchQuery = { sql: string; params: SqlParam[]; method: string }

/**
 * AI-generated (GPT-5.3-codex).
 */
export type SqlError = 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ SqlProxy: string } | 
/**
 * AI-generated (GPT-5.3-codex).
 */
{ LockPoison: string }

export type SqlParam = "Null" | { Bool: boolean } | { Int: number } | { Float: number } | { Text: string }

export type SqlQueryResult = { rows: SqlValue[][] }

export type SqlValue = "Null" | { Bool: boolean } | { Int: number } | { Float: number } | { Text: string } | { Blob: number[] }

/**
 * Identifier for a timeslot.
 */
export type TimeslotId = number

const ARGS_MAP = { '':'{"pause_solve_session":["session_id"],"sql":["sql","params","method"],"sql_batch":["queries"],"start_solve_session":["on_new_timetable","locked_slots"],"stop_solve_session":["session_id"]}' }
export type Router = { "": {pause_solve_session: (sessionId: number) => Promise<null>, 
sql: (sql: string, params: SqlParam[], method: string) => Promise<SqlQueryResult>, 
sql_batch: (queries: SqlBatchQuery[]) => Promise<SqlQueryResult[]>, 
start_solve_session: (onNewTimetable: TAURI_CHANNEL<NewTimetableUpdate>, lockedSlots: LockedTimetableSlot[]) => Promise<SolveSessionStart>, 
stop_solve_session: (sessionId: number) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
