CREATE TABLE same_time_exam (
  exam1_id INTEGER NOT NULL,
  exam2_id INTEGER NOT NULL,
  PRIMARY KEY (exam1_id, exam2_id),
  FOREIGN KEY (exam1_id) REFERENCES exam (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (exam2_id) REFERENCES exam (id) ON DELETE CASCADE ON UPDATE CASCADE
);
